version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    network_mode: host
    environment:
      - DEBUG=True
      - DB_HOST=localhost
      - DB_NAME=tinnova
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    restart: unless-stopped

