# Generated by Django 4.2.16 on 2025-08-28 23:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Marca')),
                ('ativo', models.BooleanField(default=True, verbose_name='Marca Ativa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(max_length=100, verbose_name='Nome do Veículo')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='Ano deve ser maior que 1900'), django.core.validators.MaxValueValidator(2030, message='Ano não pode ser maior que 2030')], verbose_name='Ano')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor do Veículo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['marca'], name='core_veicul_marca_i_edb74b_idx'), models.Index(fields=['ano'], name='core_veicul_ano_217ec7_idx'), models.Index(fields=['vendido'], name='core_veicul_vendido_20e89d_idx'), models.Index(fields=['created'], name='core_veicul_created_464895_idx')],
            },
        ),
    ]
