# Generated by Django 4.2.16 on 2025-08-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='veiculo',
            name='core_veicul_marca_i_edb74b_idx',
        ),
        migrations.RemoveIndex(
            model_name='veiculo',
            name='core_veicul_ano_217ec7_idx',
        ),
        migrations.RemoveIndex(
            model_name='veiculo',
            name='core_veicul_vendido_20e89d_idx',
        ),
        migrations.RemoveIndex(
            model_name='veiculo',
            name='core_veicul_created_464895_idx',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(verbose_name='Ano'),
        ),
    ]
